INVALID_FOLDER_PATH = "The provided path is not valid, please provide a valid folder path"
EMPTY_FOLDER = "The provided folder is Empty"
NO_LOG_FILES = "The provided folder doesn't have any log files, please provide a valid log folder"
PROCESSING = "Processing"
TOTAL_LOG_FILE_FOUND = "Total Log files found"
INVALID_FOLDER_COUNT="Invalid files found"
LOG_FILE_EXTENSION = ".log"
